---
- name: Verify MongoDB service and port
  hosts: mongo
  gather_facts: no
  become: yes
  tasks:
    - name: Collect service facts
      ansible.builtin.service_facts:

    - name: Assert mongod service exists
      ansible.builtin.assert:
        that:
          - "'mongod.service' in ansible_facts.services"
        fail_msg: "mongod.service not found (MongoDB not installed?)"

    - name: Assert mongod is running
      ansible.builtin.assert:
        that:
          - ansible_facts.services['mongod.service'].state == 'running'
        fail_msg: "mongod is not running"

    - name: Check port 27017 is listening
      ansible.builtin.shell: "ss -ltn '( sport = :27017 )' | grep -q 27017 || netstat -ltnp | grep -q 27017"
      register: portcheck
      changed_when: false
      failed_when: portcheck.rc != 0

    - name: Show mongod version
      ansible.builtin.command: mongod --version
      register: ver
      changed_when: false

    - ansible.builtin.debug:
        var: ver.stdout_lines
